site_name: Pyger
site_url: https://pyger.codes
site_author: GerProgrammer
site_description: The awesome python library to create Telegram Bots based on pyrogram. Updates available at https://t.me/pyger
repo_name: unknownusernametopick/pyger
repo_url: https://github.com/unknownusernametopick/pyger
#edit_uri: ""
copyright: Copyright &copy; 2022, <a href='http://github.com/unknownusernametopick' target='_blank'>Ger Programmer</a>

theme:
  name: 'material'
  custom_dir: docs/overrides
  favicon: images/favicon.ico
  logo: images/Pyger.png
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - navigation.sections
    - content.code.annotate
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
#    - navigation.tabs
#    - navigation.instant
#    - navigation.tabs.sticky
#    - toc.integrate
#    - header.autohide
#    - content.tabs.link

nav:
  - Home: index.md
  - Introduction:
    - introduction/quickstart.md
    - introduction/install.md
  - Getting Started:
    - start/boilerplate.md
    - start/variables.md
    - start/running-bot.md
    - start/examples.md
  - Topics:
    - topics/settings.md
    - topics/customization.md
    - topics/plugins.md
    - topics/bot-menu.md
  - Classes:
    - classes/ger.md
    - classes/message.md
  - Decorators:
    - decorators/index.md
    - decorators/command.md
    - decorators/callback.md
    - decorators/inline.md
#    - decorators/admins.md
  - Databases:
    - databases/index.md
    - Using Postgres: databases/postgres.md
    - databases/telegram-as-database.md
    - databases/tinydb.md
  - Helpers:
    - helpers/index.md
    - helpers/patch.md
    - helpers/process.md
    - helpers/stickers.md
  - bots.md
  - FAQ: meta/faqs.md
  - ChangeLog:
    - meta/changelog/index.md
    - meta/older-releases.md

markdown_extensions:
  - codehilite:
      css_class: highlight
  - admonition
  - meta
  - pymdownx.highlight

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false

extra_css:
  - css/custom.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unknownusernametopick
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyger/
    - icon: fontawesome/brands/telegram
      link: https://t.me/NNGerBots
