__version__ = "1.2.1"
__description__ = "An add-on extension to Pyrogram for absolute beginners"
__copyright__ = "Copyright (C) 2021-2022 Nigger Bots <https://github.com/unknownusernametopick>"
__license__ = "GNU General Public License v3 or later (GPLv3+)"
__terms__ = f"PyNigger is free software and comes with ABSOLUTELY NO WARRANTY. \nLicensed under the terms of {__license__}."
